apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: numeric-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/tungnns/devsecops-infra.git
    targetRevision: HEAD
    path: ./manifests/numeric
   
  destination:
    server: https://kubernetes.default.svc
    namespace: numeric-app

  syncPolicy:
    syncOptions:
      - CreateNamespace=true  
    automated:
      prune: true
      selfHeal: true