apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: numeric
  name: numeric-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: numeric
  strategy: {}
  template:
    metadata:
      labels:
        app: numeric
    spec:
      volumes:
      - name: vol
        emptyDir: {}
      serviceAccountName: default
      containers:
      - image: tungnns/numeric-app:93f57c9eb05974808eceb1f9ca44ca8e7360628c
        name: numeric-container
        resources: 
          requests:
            cpu: 512m
            memory: 512Mi
          limits:
            cpu: 512m 
            memory: 512Mi
        volumeMounts:
        - mountPath: /tmp
          name: vol
        securityContext:
          runAsNonRoot: true
          runAsUser: 100
          readOnlyRootFilesystem: true
        