apiVersion: v1
kind: Service
metadata:
  labels:
    app: numeric
  name: numeric-svc
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: numeric
  type: ClusterIP